// website/src/lib/components/timeline/TimelineScrubber.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let start: Date;
  export let end: Date;
  export let current: Date;
  export let onChange: (time: Date) => void;

  let containerElement: HTMLDivElement;
  let isDragging = false;

  $: totalDuration = end.getTime() - start.getTime();
  $: currentProgress = (current.getTime() - start.getTime()) / totalDuration;

  function updateTime(clientX: number) {
    if (!containerElement) return;

    const rect = containerElement.getBoundingClientRect();
    const progress = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    const newTime = new Date(start.getTime() + progress * totalDuration);
    onChange(newTime);
  }

  function handlePointerDown(e: PointerEvent) {
    if (!containerElement) return;
    isDragging = true;
    containerElement.setPointerCapture(e.pointerId);
    updateTime(e.clientX);
  }

  function handlePointerMove(e: PointerEvent) {
    if (!isDragging) return;
    updateTime(e.clientX);
  }

  function handlePointerUp(e: PointerEvent) {
    if (!containerElement) return;
    isDragging = false;
    containerElement.releasePointerCapture(e.pointerId);
  }
</script>

<div 
  bind:this={containerElement}
  class="relative h-6 group cursor-pointer"
  on:pointerdown={handlePointerDown}
  on:pointermove={handlePointerMove}
  on:pointerup={handlePointerUp}
>
  <!-- Track Background -->
  <div class="absolute inset-0 my-2.5 rounded-full bg-white/10 overflow-hidden">
    <!-- Progress Bar -->
    <div 
      class="absolute h-full bg-white/30 transition-all duration-75"
      style:width="{currentProgress * 100}%"
    />
  </div>

  <!-- Thumb -->
  <div 
    class="absolute top-0 -ml-2 w-4 h-4 rounded-full bg-white border border-white/20 shadow-lg
           transform transition-transform duration-75 hover:scale-110"
    style:left="{currentProgress * 100}%"
  />
</div>

// Refrence Code NOT PART OF THE CODE BASE/timeline/TimelineScrubber.tsx
import { useRef, useCallback, useEffect } from 'react';

interface TimelineScrubberProps {
  start: Date;
  end: Date;
  current: Date;
  onChange: (time: Date) => void;
}

export function TimelineScrubber({ start, end, current, onChange }: TimelineScrubberProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const isDragging = useRef(false);

  const totalDuration = end.getTime() - start.getTime();
  const currentProgress = (current.getTime() - start.getTime()) / totalDuration;

  const handlePointerDown = useCallback((e: React.PointerEvent) => {
    if (!containerRef.current) return;
    isDragging.current = true;
    containerRef.current.setPointerCapture(e.pointerId);
    updateTime(e);
  }, []);

  const handlePointerMove = useCallback((e: React.PointerEvent) => {
    if (!isDragging.current) return;
    updateTime(e);
  }, []);

  const handlePointerUp = useCallback((e: React.PointerEvent) => {
    if (!containerRef.current) return;
    isDragging.current = false;
    containerRef.current.releasePointerCapture(e.pointerId);
  }, []);

  const updateTime = useCallback((e: React.PointerEvent) => {
    if (!containerRef.current) return;

    const rect = containerRef.current.getBoundingClientRect();
    const progress = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
    const newTime = new Date(start.getTime() + progress * totalDuration);
    onChange(newTime);
  }, [start, totalDuration, onChange]);

  return (
    <div 
      ref={containerRef}
      className="relative h-6 group cursor-pointer"
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
    >
      {/* Track Background */}
      <div className="absolute inset-0 my-2.5 rounded-full bg-surface-light overflow-hidden">
        {/* Progress Bar */}
        <div 
          className="absolute h-full bg-primary transition-all duration-75"
          style={{ width: `${currentProgress * 100}%` }}
        />
      </div>

      {/* Thumb */}
      <div 
        className="absolute top-0 -ml-2 w-4 h-4 rounded-full bg-primary border-2 border-white shadow-lg
                   transform transition-transform duration-75 hover:scale-110"
        style={{ left: `${currentProgress * 100}%` }}
      />
    </div>
  );
}
