// Refrence Code NOT PART OF THE CODE BASE/Animation  NOT PART OF THE CODE BASE/timeline/TimeFilter.tsx
import { format } from 'date-fns';
import { useAnimation } from '../../context/AnimationContext';

export function TimeFilter() {
  const { gpsData, setTimeFilter } = useAnimation();

  if (!gpsData) return null;

  const { timeRange } = gpsData;
  const formatDateTime = (date: Date) => format(date, "yyyy-MM-dd'T'HH:mm");

  const handleFilterChange = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const start = new Date(formData.get('start') as string);
    const end = new Date(formData.get('end') as string);

    // Ensure valid date range
    if (!isNaN(start.getTime()) && !isNaN(end.getTime()) && start <= end) {
      setTimeFilter({ start, end });
    }
  };

  const handleReset = () => {
    setTimeFilter(null);
  };

  return (
    <form 
      onSubmit={handleFilterChange} 
      className="flex items-center gap-2"
    >
      <div className="flex items-center gap-2">
        <input
          type="datetime-local"
          name="start"
          defaultValue={formatDateTime(timeRange.start)}
          min={formatDateTime(timeRange.start)}
          max={formatDateTime(timeRange.end)}
          className="w-44 bg-surface border border-surface-light rounded px-2 py-1.5 text-sm
                   focus:outline-none focus:ring-2 focus:ring-primary/20"
        />
        <span className="text-text-secondary">to</span>
        <input
          type="datetime-local"
          name="end"
          defaultValue={formatDateTime(timeRange.end)}
          min={formatDateTime(timeRange.start)}
          max={formatDateTime(timeRange.end)}
          className="w-44 bg-surface border border-surface-light rounded px-2 py-1.5 text-sm
                   focus:outline-none focus:ring-2 focus:ring-primary/20"
        />
      </div>
      <div className="flex items-center gap-2">
        <button
          type="submit"
          className="px-3 py-1.5 bg-primary text-white rounded text-sm hover:bg-primary/90
                   transition-colors"
        >
          Apply
        </button>
        <button
          type="button"
          onClick={handleReset}
          className="px-3 py-1.5 text-text-secondary hover:text-text-primary text-sm
                   transition-colors"
        >
          Reset
        </button>
      </div>
    </form>
  );
}

// website/src/lib/components/timeline/TimeFilter.svelte
<script lang="ts">
  import { format } from 'date-fns';
  import { animationStore, type TimeRange } from '$lib/stores/animation';

  export let timeRange: TimeRange;

  const formatDateTime = (date: Date) => format(date, "yyyy-MM-dd'T'HH:mm");

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const start = new Date(formData.get('start') as string);
    const end = new Date(formData.get('end') as string);

    // Ensure valid date range
    if (!isNaN(start.getTime()) && !isNaN(end.getTime()) && start <= end) {
      animationStore.setTimeFilter({ start, end });
    }
  }

  function handleReset() {
    animationStore.setTimeFilter(null);
  }
</script>

<form 
  on:submit={handleSubmit}
  class="flex items-center gap-2"
>
  <div class="flex items-center gap-2">
    <input
      type="datetime-local"
      name="start"
      value={formatDateTime(timeRange.start)}
      min={formatDateTime(timeRange.start)}
      max={formatDateTime(timeRange.end)}
      class="h-8 w-44 bg-white/10 hover:bg-white/20 border border-white/10 rounded px-2 text-sm text-white
             focus:outline-none focus:ring-1 focus:ring-white/30"
    />
    <span class="text-white/70">to</span>
    <input
      type="datetime-local"
      name="end"
      value={formatDateTime(timeRange.end)}
      min={formatDateTime(timeRange.start)}
      max={formatDateTime(timeRange.end)}
      class="h-8 w-44 bg-white/10 hover:bg-white/20 border border-white/10 rounded px-2 text-sm text-white
             focus:outline-none focus:ring-1 focus:ring-white/30"
    />
  </div>
  <div class="flex items-center gap-2">
    <button
      type="submit"
      class="h-8 px-3 bg-white/10 hover:bg-white/20 text-white rounded text-sm
             transition-colors"
    >
      Apply
    </button>
    <button
      type="button"
      on:click={handleReset}
      class="h-8 px-3 text-white/70 hover:text-white text-sm
             transition-colors"
    >
      Reset
    </button>
  </div>
</form>
